API_KEY = ''
BOT_TOKEN = ''
PATH_DATA = './data'
NAME_DATA_PARSED = 'parsed.txt'
NAME_DATA_DF = 'parsed_df.csv'
NAME_DATA_SUMMARY = 'summary.csv'
NAME_PATTERN = './patterns/keynote.pptx'
NAME_PRESENTATION = './data/pp_presentation.pptx'

model_sum = 'IlyaGusev/mbart_ru_sum_gazeta'
